spring.datasource:
  jdbcUrl: jdbc:mysql://localhost:3306/shop?useSSL=false
  driverClassName: com.mysql.cj.jdbc.Driver
  password: password
  username: root

  config:
    activate:
      on-profile: prod

spring.datasource2:
  jdbcUrl: jdbc:h2:mem:test
  driverClassName: org.h2.Driver
  password: password
  username: sa

  config:
    activate:
      on-profile: test

spring.jpa:
  generate.ddl: true
  database: default
  properties:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      jdbc:
        batch_size: 100
      order_inserts: true
  show-sql: true

spring.h2:
  console:
    enabled: true
    path: /h2

spring.jackson:
  deserialization:
    fail-on-unknown-properties: true


spring:
  profiles:
    active: prod
