spring:

  datasource:
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    jdbc-url: jdbc:mysql://localhost:3306/shop?useSSL=false

  datasource2:
    username: sa
    jdbc-url: jdbc:h2:mem:test
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: 'true'
    database: default
    properties:
      hibernate:
        jdbc:
          batch_size: '100'
        order_inserts: 'true'
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: 'false'
    show-sql: 'true'
  h2:
    console:
      path: /h2
      enabled: 'true'
  jackson:
    deserialization:
      fail-on-unknown-properties: 'true'

  profiles:
    active: prod

springdoc:
  api-docs:
    path: /shop-docs
